services:
  quetre:
    container_name: quetre
    image: ghcr.io/shindouj/quetre:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000" # Replace with "3000:3000" if you don't use a reverse proxy
    environment:
      - "NODE_ENV=production"
      - "PORT=3000"
      - "CACHE_PERIOD=1h"
      - "REDIS_URL=quetre-redis:6379"
      - "REDIS_TTL=3600"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - quetre
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000 || exit 1
      interval: 1m
      timeout: 3s
    depends_on:
      quetre-redis:
        condition: service_healthy
        restart: true
  quetre-redis:
    container_name: quetre-redis
    image: docker.io/redis:alpine
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping
      interval: 30s
      timeout: 5s
      retries: 2
    networks:
      - quetre
networks:
  quetre:
